language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit -v -c tests/travis/travis.xml $PHPUNIT_FLAGS

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
