---
- name: Install vim
  apt: name=vim state=present

- name: Install curl
  apt: name=curl state=present

- name: Install unzip
  apt: name=unzip state=present

- name: Install rsync
  apt: name=rsync state=present

- name: Install git
  apt: name=git-core state=present
