---

pf3server_url: pinballfinder.org
pf3server_runmode: production
pf3server_docroot: /var/www/pf3
pf3server_ssl: /home/ubuntu/ssl/pf3/apns
pf3server_gamedict_path: /var/www/pinballfinder.org/gamedict.txt
pf3server_log_directory: /home/ubuntu/logs

pf3server_deploy_host: web-prod-lamp
pf3server_deploy_user: ubuntu

pf3server_db_name: pf3_server
