---
- name: Add nginx repository key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add nginx repository
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx' state=present

- name: Add nginx src repository
  apt_repository: repo='deb-src http://nginx.org/packages/ubuntu/ trusty nginx' state=present

- name: Install nginx
  apt: name=nginx state=present

- name: Create /etc/nginx/nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644

- name: Create /etc/nginx/sites-available
  file: path=/etc/nginx/sites-available state=directory owner=root group=root mode=0644

- name: Create /etc/nginx/sites-enabled
  file: path=/etc/nginx/sites-enabled state=directory owner=root group=root mode=0644

- name: Remove default nginx site
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify: Reload nginx

- name: Set nginx mime.types
  template: src=mime.types dest=/etc/nginx/mime.types
  notify: Reload nginx

- name: Ensure nginx service state
  service: name=nginx state=started

#- name: Create /var/www
#  file: path=/var/www state=directory owner=root group=www-data mode=2775
