- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  pre_tasks:
    - apt: update_cache=yes
  roles:
    - common

- name: configure and deploy pf3server
  hosts: pf3server
  remote_user: root
  roles:
    - pf3server
  vars_files:
    - ../config.yml
    - ../credentials.yml
