---
- name: Install xhprof
  command: pecl install -f channel://pecl.php.net/xhprof-0.9.4 creates=/usr/lib/php5/20131226/xhprof.so
  notify: Restart php

- name: Create xhprof.ini
  template: src=xhprof.ini.j2 dest=/etc/php5/mods-available/xhprof.ini
  notify: Restart php

- name: Enable fpm xhprof.ini
  file: src=/etc/php5/mods-available/xhprof.ini dest=/etc/php5/fpm/conf.d/30-xhprof.ini owner=root group=root state=link
  notify: Restart php

- name: Enable cli xhprof.ini
  file: src=/etc/php5/mods-available/xhprof.ini dest=/etc/php5/cli/conf.d/30-xhprof.ini owner=root group=root state=link

- name: Copy xhprof_html
  copy: src=xhprof_html dest=/usr/share/php

- name: Copy xhprof_lib
  copy: src=xhprof_lib dest=/usr/share/php

- name: Create xhprof vhost entry
  template: src=xhprof.j2 dest=/etc/nginx/sites-available/xhprof owner=root group=root mode=644
  notify: Reload nginx

- name: Enable xhprof vhost
  file: src=/etc/nginx/sites-available/xhprof dest=/etc/nginx/sites-enabled/xhprof state=link owner=root group=root mode=644
  notify: Reload nginx
