ALTER TABLE game ADD ipdb INT DEFAULT NULL;
UPDATE game SET ipdb = id WHERE ipdb IS NULL;
ALTER TABLE game CHANGE id id INT AUTO_INCREMENT NOT NULL;
CREATE UNIQUE INDEX UNIQ_232B318CBCF3411D ON game (abbreviation);
